# .github/workflows/process-photos.yml
name: Process Photos

on:
  push:
    paths:
      - "src/photos/**"
  workflow_dispatch:

jobs:
  process-photos:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Pillow requests

      - name: Process new photos
        run: |
          python scripts/process-photo.py
        env:
          # You can add AI API keys here when needed:
          # AI_API_KEY: ${{ secrets.AI_API_KEY }}

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/data/photos.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update photo data"
          git push
